### ISSUE TITLE
If portal is in the same sector as player, the sector might unload

### ISSUE THREAD

**Issue by MagnusCaligo** [MagnusCaligo/Outer_Portals#8]
Currently we unload the sectors tied to an output portal when the player doesn't look at it. However, if the output portal is in the same sector as the player (either the portal is a mirror or just leads to the same sector) this will result in the sector de-loading around the player when they look away.

**Comment by JohnCorby** [comment]
fixed using same logic as NomaiRemoteCameraStreaming
